### PR TITLE
Add a filter to the statuses

### PR DESCRIPTION
**Pull request by LankyBox01**
Please import the anti-profanity plug-in to the dashboard in order for this to work.

https://github.com/CodeGuy92/anti-profanity#readme
Docs are here ^^^

### CODE REVIEW

**Comment by FunctionalMetatable** [comment]
Please PR for issues that are marked "help wanted".

**Comment by LankyBox01** [comment]
> Please PR for issues that are marked "help wanted".

I didn't know that, tho

**Comment by jeffalo** [comment]
@FunctionalMetatable is right. i dont think this works anyways, filterWords is not defined.

**Comment by CodeGuy92** [comment]
why

**Comment by LankyBox01** [comment]
you have to import it first

**Comment by LankyBox01** [comment]
did you read the docs

**Comment by FunctionalMetatable** [comment]
There is a number of flaws in the suggested solution:
1. The code itself contains **swear words.** If jeffalo was to implement this, it is possible for the ST to **ban** linking to this repository.
2. `String.replaceAll` **cannot function** in Node.js. The only way around this is to use RegExp. (There are many instances of `replaceAll` in this code.)
3. **Node.js cannot import scripts from a URL.**
4.  The keyword `var` is repeated tons of times
5. `window` is undefined in Node.js
6. If ran in a client-side environment, it writes to the window object itself, which is kinda bad

Take the above as constructive criticism.

**Comment by cobaltt7** [comment]
> 1. The code itself contains **swear words.** If jeffalo was to implement this, it is possible for the ST to **ban** linking to this repository.

yes, you would have to rot13 or otherwise encode the swears, then decode them in the code.

> 2. `String.replaceAll` **cannot function** in Node.js. The only way around this is to use RegExp. (There are many instances of `replaceAll` in this code.)

not entirely true. you just need a version of node that supports it, and seeing as `replaceAll` is pretty new...yeah use `replace`

> 3. **Node.js cannot import scripts from a URL.**

you can `npm install` from git **if there is a package.json**

**Pull request closed without merging**
